namespace:
  name: mlbuffet

images:
  inferrer: IMAGE_MLBUFFET_INFERRER
  modelhost: IMAGE_MLBUFFET_MODELHOST
  storage: IMAGE_MLBUFFET_STORAGE
  metrics: IMAGE_MLBUFFET_METRICS
  cache:  IMAGE_MLBUFFET_CACHE
  trainer: IMAGE_MLBUFFET_TRAINER
  imagePullPolicy: Always

apiVersion:
  deployment: apps/v1
  service: v1
  role: rbac.authorization.k8s.io/v1
  serviceAccount: v1
  roleBinding: rbac.authorization.k8s.io/v1

role:
  scheduler:
    name: schedule-modelhosts
    resources:
      - pods
      - deployments
      - services
    verbs:
      - list
      - get
      - delete
      - create
      - patch
  trainer:
    name: trainer-apoptosis
    resources:
      - pods
    verbs:
      - delete

roleBinding:
  scheduler:
    name: modelhost-rolebinding
  trainer:
    name: trainer-rb

serviceAccount:
  scheduler:
    name: modelhost-creator
  trainer:
    name: trainer-sa

orchestratorType: "KUBERNETES"

cache:
  name: cache
  service:
    ports:
      protocol: TCP
      port: 6379
      targetPort: 6379
  deployment:
    replicas: 1

inferrer:
  name: inferrer
  service:
    ports:
      protocol: TCP
      port: 8000
      targetPort: 8000
  deployment: 
    replicas: 1

modelhost:
  name: modelhost
  service:
    ports:
      protocol: TCP
      port: 8000
      targetPort: 8000
  deployment: 
    replicas: 1

storage:
  name: storage
  service:
    ports:
      protocol: TCP
      port: 8000
      targetPort: 8000
  deployment: 
    replicas: 1

metrics:
  name: metrics
  service:
    ports:
      protocol: TCP
      port: 9090
      targetPort: 9090
  deployment: 
    replicas: 1
