apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modelhostpvc
  namespace: mlbuffet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: localstorage
