apiVersion: v1
kind: PersistentVolume
metadata:
  name: models
  namespace: mlbuffet
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/models/
