apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferrer
  namespace: mlbuffet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inferrer
  template:
    metadata:
      labels:
        app: inferrer
    spec:
      containers:
        - name: inferrer
          image: inferrer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: OVERLAY_NETWORK
              value: "172.17.0.0/24"
