apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferrer
  namespace: mlbuffet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlbuffet_inferrer
  template:
    metadata:
      labels:
        app: mlbuffet_inferrer
    spec:
     serviceAccountName: pod-scheduler  
     containers:
        - name: inferrer
          image: IMAGE_MLBUFFET_INFERRER
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ORCHESTRATOR
              value: "KUBERNETES"
            - name: IMAGE_MLBUFFET_TRAINER
              value: IMAGE_MLBUFFET_TRAINER_NAME

---

apiVersion: v1
kind: Service
metadata:
  name: inferrer
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_inferrer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort

