apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlbuffet

resources:
  - mlbuffet_namespace.yaml
  - rbac.yaml
  - modelhost.yaml
  - inferrer.yaml
  - cache.yaml
  - metrics.yaml
  - storage.yaml

images:
  # Modelhost image name
  - name: IMAGE_MLBUFFET_MODELHOST
    newName: IMAGE_MLBUFFET_MODELHOST
  # Inferrer image name
  - name: IMAGE_MLBUFFET_INFERRER
    newName: IMAGE_MLBUFFET_INFERRER
  # Cache image name
  - name: IMAGE_MLBUFFET_CACHE
    newName: IMAGE_MLBUFFET_CACHE
  # Metrics image name
  - name: IMAGE_MLBUFFET_METRICS
    newName: IMAGE_MLBUFFET_METRICS
  # Storage image name
  - name: IMAGE_MLBUFFET_STORAGE
    newName: IMAGE_MLBUFFET_STORAGE
  # Trainer image name into inferrer.yaml
  - name: IMAGE_MLBUFFET_TRAINER_NAME
    newName: IMAGE_MLBUFFET_TRAINER
