apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlbuffet

resources:
  - mlbuffet_namespace.yaml
  - rbac.yaml
  - inferrer.yaml
  - cache.yaml
  - metrics.yaml
  - storage.yaml

images:
  # Inferrer image name
  - name: IMAGE_MLBUFFET_INFERRER
    newName: localhost:5000/mlbuffet_inferrer
  # Cache image name
  - name: IMAGE_MLBUFFET_CACHE
    newName: localhost:5000/mlbuffet_cache
  # Metrics image name
  - name: IMAGE_MLBUFFET_METRICS
    newName: localhost:5000/mlbuffet_metrics
  # Storage image name
  - name: IMAGE_MLBUFFET_STORAGE
    newName: localhost:5000/mlbuffet_storage
