apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelhost
  namespace: mlbuffet
  labels:
    app: mlbuffet_modelhost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlbuffet_modelhost
  template:
    metadata:
      labels:
        app: mlbuffet_modelhost
    spec:
      containers:
        - name: modelhost
          image: $(echo $MODELHOST)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /usr/src/flask_app/models
              name: models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: modelhostpvc

---

apiVersion: v1
kind: Service
metadata:
  name: modelhost
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_modelhost
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
  internalTrafficPolicy: Cluster

