apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: mlbuffet
rules:
  - apiGroups: ["apps"]
    resources: ["pods","deployments"]
    verbs:
      - get
      - list
      - delete
      - create
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
  namespace: mlbuffet
subjects:
  - kind: ServiceAccount
    name: pod-scheduler
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-scheduler
  namespace: mlbuffet
