apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: mlbuffet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlbuffet_storage
  template:
    metadata:
      labels:
        app: mlbuffet_storage
    spec:
      serviceAccountName: pod-scheduler
      containers:
        - name: storage
          image: IMAGE_MLBUFFET_STORAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8000 
          env:
            - name: ORCHESTRATOR
              value: "KUBERNETES"
---

apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_storage
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort

