version: '3'
services:
  inferrer:
    image: mlbuffet_inferrer
    hostname: "{{.Service.Name}}_{{.Task.Slot}}"
    environment:
      OVERLAY_NETWORK: '10.0.13.0/24'
    networks:
      - mlbuffet_overlay
    ports:
      - "8002:8000"

  modelhost:
    image: mlbuffet_modelhost
    hostname: "{{.Service.Name}}_{{.Task.Slot}}"
    deploy:
      replicas: 1
    networks:
      - mlbuffet_overlay
    ports:
      - "8004:8000"
    volumes:
      - ../../modelhost/flask_app/models:/usr/src/flask_app/models

  prometheus:
    image: mlbuffet_prometheus
    hostname: "{{.Service.Name}}_{{.Task.Slot}}"
    networks:
      - mlbuffet_overlay
    ports:
      - "9091:9090"
  cache:
    image: mlbuffet_cache
    hostname: "{{.Service.Name}}_{{.Task.Slot}}"
    networks:
      - mlbuffet_overlay

  storage:
    image: mlbuffet_storage
    hostname: "{{.Service.Name}}_{{.Task.Slot}}"
    networks:
      - mlbuffet_overlay
    ports:
      - "8006:8000"
    volumes:
      - ../../modelhost/flask_app/models:/usr/src/flask_app/modelhostfiles



networks:
  mlbuffet_overlay:
    driver: overlay
    external: true
