apiVersion: {{ .Values.apiVersion.deployment }}
kind: Deployment
metadata:
  name: {{ .Values.cache.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.cache.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.namespace.name}}_{{ .Values.cache.name}}
      chart: "{{ .Chart.Name}}_{{ .Chart.Version}}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
  template:
    metadata:
      labels:
        app: {{.Values.namespace.name}}_{{ .Values.cache.name }}
        chart: "{{ .Chart.Name}}_{{ .Chart.Version}}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
        - name: {{ .Values.cache.name}}
          image: {{ .Values.images.cache}}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.cache.service.ports.port}}

---
apiVersion: {{ .Values.apiVersion.service }}
kind: Service
metadata:
  name: {{ .Values.cache.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{.Values.namespace.name}}_{{ .Values.cache.name}}
  ports:
  - protocol: {{ .Values.cache.service.ports.protocol}}
    port: {{ .Values.cache.service.ports.port}}
    targetPort: {{ .Values.cache.service.ports.targetport}}
  type: NodePort
