apiVersion: {{ .Values.apiVersion.deployment }}
kind: Deployment
metadata:
  name: {{ .Values.metrics.name}}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{.Values.namespace.name}}_{{ .Values.metrics.name}}
spec:
  replicas: {{ .Values.metrics.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.namespace.name}}_{{ .Values.metrics.name}}
  template:
    metadata:
      labels:
        app: {{.Values.namespace.name}}_{{ .Values.metrics.name}}
    spec:
      containers:
      - name: {{ .Values.metrics.name }}
        image: {{ .Values.images.metrics}}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        ports: 
        - containerPort: {{ .Values.metrics.service.ports.port}}

---

apiVersion: {{ .Values.apiVersion.service }}
kind: Service
metadata:
  name: {{ .Values.metrics.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{.Values.namespace.name}}_{{ .Values.metrics.name}}
  ports:
  - protocol: {{ .Values.metrics.service.ports.protocol}}
    port: {{ .Values.metrics.service.ports.port}}
    targetPort: {{ .Values.metrics.service.ports.targetPort}}
  type: ClusterIP

