apiVersion: {{ .Values.apiVersion.deployment }}
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.metrics.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.metrics.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.metrics.name}}
      chart: "{{ .Chart.Name}}_{{ .Chart.Version}}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.metrics.name}}
        chart: "{{ .Chart.Name}}_{{ .Chart.Version}}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - name: {{ .Values.metrics.name }}
        image: {{ .Values.images.metrics}}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        ports: 
        - containerPort: {{ .Values.metrics.service.ports.port}}

---

apiVersion: {{ .Values.apiVersion.service }}
kind: Service
metadata:
  name: {{ .Values.metrics.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.metrics.name}}
  ports:
  - protocol: {{ .Values.metrics.service.ports.protocol}}
    port: {{ .Values.metrics.service.ports.port}}
    targetPort: {{ .Values.metrics.service.ports.targetPort}}
  type: NodePort

