apiVersion: {{ .Values.apiVersion.role }}
kind: Role
metadata:
  name: {{ .Values.role.scheduler.name}}
  namespace: {{ .Values.namespace.name }}
rules:
  - apiGroups: ["", "apps"]
    resources: {{- range .Values.role.scheduler.resources }}
    - {{ . | title | lower}}
    {{- end}}
    verbs: {{- range .Values.role.scheduler.verbs}}
    - {{ . | title | lower }}
    {{- end}}

---

apiVersion: {{ .Values.apiVersion.roleBinding}}
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.scheduler.name}}
  namespace: {{ .Values.namespace.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.scheduler.name}}
roleRef:
  kind: Role
  name: {{ .Values.role.scheduler.name}}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: {{ .Values.apiVersion.serviceAccount}}
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.scheduler.name}}
  namespace: {{ .Values.namespace.name }}

---

apiVersion: {{ .Values.apiVersion.role }}
kind: Role
metadata:
  name: {{ .Values.role.trainer.name}}
  namespace: {{ .Values.namespace.name }}
rules:
  - apiGroups: ["", "apps"]
    resources: {{- range .Values.role.trainer.resources }}
    - {{ . | title | lower}}
    {{- end}}
    verbs: {{- range .Values.role.trainer.verbs}}
    - {{ . | title | lower }}
    {{- end}}

---

apiVersion: {{ .Values.apiVersion.roleBinding}}
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.trainer.name}}
  namespace: {{ .Values.namespace.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.trainer.name}}
roleRef:
  kind: Role
  name: {{ .Values.role.trainer.name}}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: {{ .Values.apiVersion.serviceAccount}}
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.trainer.name}}
  namespace: {{ .Values.namespace.name }}
