version: '3'
services:

  inferrer:
    container_name: inferrer
    restart: always
    build: ../inferrer/flask_app
    ports:
    - ${INFERRER_API_BIND_TO_PORT}:8000
    volumes:
      - ../inferrer/logs:/home/logs
    env_file:
    - .env

  modelhost_1:
    container_name: modelhost_1
    restart: always
    build: ../modelhost/flask_app
    ports:
    - ${MODELHOST_API_BIND_TO_PORT}:8000

    volumes:
      - ../modelhost/logs:/home/logs
      - ../modelhost/flask_app/models:/usr/src/flask_app/models
    env_file:
    - .env

  prometheus:
    container_name: prometheus-fractal
    restart: always
    build: ../metrics/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090

  nginx:
    container_name: nginx-fractal
    restart: always
    build: ../inferrer/nginx
    ports:
      - "80:80"
    depends_on:
      - inferrer
    volumes:
      - ./service-configurations/nginx-config/:/etc/nginx/conf.d/
