services:

  inferrer:
    image: swarm.zylk.net/fractalml/deploy_inferrer
    environment:
      FLASK_PORT: '8443'
      INFERRER_API_BIND_TO_PORT: '8002'
      LOAD_BALANCER_PORT: '80'
      MODELHOST_API_BIND_TO_PORT: '8004'
      PROMETHEUS_PORT: '9090'
      INFERRER_ENDPOINT: 'fractalml_inferrer'
      MODELHOST_ENDPOINT: 'fractalml_modelhost'
      OVERLAY_NETWORK: '10.0.13.0/24'
    networks:
      - fractal_overlay
    ports:
      - "8002:8000"

  modelhost:
    image: swarm.zylk.net/fractalml/deploy_modelhost
    environment:
      FLASK_PORT: '8443'
      INFERRER_API_BIND_TO_PORT: '8002'
      LOAD_BALANCER_PORT: '80'
      MODELHOST_API_BIND_TO_PORT: '8004'
      PROMETHEUS_PORT: '9090'
    deploy:
      replicas: 4
    networks:
      - fractal_overlay
    ports:
      - "8004:8000"

  prometheus:
    image: swarm.zylk.net/fractalml/deploy_prometheus
    networks:
      - fractal_overlay
    ports:
      - "9091:9090"

networks:
  fractal_overlay:
    driver: overlay
    external: true

version: '3'