services:

  inferrer:
    image: deploy_inferrer
    environment:
      FLASK_PORT: '8443'
      INFERRER_API_BIND_TO_PORT: '8002'
      LOAD_BALANCER_PORT: '80'
      MODELHOST_API_BIND_TO_PORT: '8004'
      NUMBER_MODELHOST_NODES: '2'
      PROMETHEUS_PORT: '9090'
      INFERRER_ENDPOINT: 'fractalml_inferrer'
      MODELHOST_ENDPOINT: 'fractalml_modelhost'
      OVERLAY_NETWORK: '10.0.13.0/24'
    networks:
            - fractaloverlay
    ports:
    - "8002:8000"

  modelhost:
    image: deploy_modelhost_1
    environment:
      FLASK_PORT: '8443'
      INFERRER_API_BIND_TO_PORT: '8002'
      LOAD_BALANCER_PORT: '80'
      MODELHOST_API_BIND_TO_PORT: '8004'
      NUMBER_MODELHOST_NODES: '2'
      PROMETHEUS_PORT: '9090'
    deploy:
      replicas: 4
    networks:
            - fractaloverlay
    ports:
    - "8004:8000"

  nginx:
    image: deploy_nginx
    depends_on:
    - inferrer
    ports:
    - "80:80"

  prometheus:
    image: deploy_prometheus
    ports:
    - "9091:9090"

networks:
  fractaloverlay:
    driver: overlay
    external: true

version: '3'
