services:

  inferrer:
    image: deploy_inferrer
    environment:
      FLASK_PORT: '8443'
      INFERRER_API_BIND_TO_PORT: '8002'
      LOAD_BALANCER_PORT: '80'
      MODELHOST_API_BIND_TO_PORT: '8004'
      NUMBER_MODELHOST_NODES: '2'
      PROMETHEUS_PORT: '9090'
      INFERRER_ENDPOINT: 'fractalml_inferrer'
      MODELHOST_ENDPOINT: 'fractalml_modelhost'
    ports:
    - "8002:8000"
    volumes:
    - /home/alfonsozylk/Escritorio/FRACTAL/GitHubFractal/fractal/FractalMLServer-Lite/inferrer/logs:/home/logs:rw

  modelhost:
    image: deploy_modelhost_1
    environment:
      FLASK_PORT: '8443'
      INFERRER_API_BIND_TO_PORT: '8002'
      LOAD_BALANCER_PORT: '80'
      MODELHOST_API_BIND_TO_PORT: '8004'
      NUMBER_MODELHOST_NODES: '2'
      PROMETHEUS_PORT: '9090'
    deploy:
      replicas: 4
    ports:
    - "8004:8000"
    volumes:
    - /home/alfonsozylk/Escritorio/FRACTAL/GitHubFractal/fractal/FractalMLServer-Lite/modelhost/logs:/home/logs:rw
    - /home/alfonsozylk/Escritorio/FRACTAL/GitHubFractal/fractal/FractalMLServer-Lite/modelhost/flask_app/models:/usr/src/flask_app/models:rw

  nginx:
    image: deploy_nginx
    depends_on:
    - inferrer
    ports:
    - "80:80"
    volumes:
    - /home/alfonsozylk/Escritorio/FRACTAL/GitHubFractal/fractal/FractalMLServer-Lite/deploy/service-configurations/nginx-config:/etc/nginx/conf.d:rw

  prometheus:
    image: deploy_prometheus
    ports:
    - "9090:9090"

networks:
  fractaloverlay:
    driver: overlay
    external: true

version: '3'
